### ISSUE TITLE
while trying to set up a replicate a100 version

### ISSUE THREAD

**Issue by yosun** [lucataco/cog-sdxl-controlnet#1]
⚠️ This model version recently failed to complete setup. Your prediction may fail to start if setup is failing consistently.

Hide logs
Loading controlnet model
Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
response.raise_for_status()
File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)

**Comment by lucataco** [comment]
Don't know about the A100, but this model is still running strong on the Nvidia A40 GPU

Make sure you run the script to download the weights locally, before you try to push to Replicate
